/* Program Description
Bingo game program where the user selects from the menu:
(1) Enter player's 6 numbers
    The user enters their own 6 numbers
(2) Generate game's 6 random numbers
    The game generates its 6 numbers
(3) Display both player and game number sets
    Show the user's numbers and the game's numbers
(4) Compare the player and game numbers
    The users numbers are compared to the game's numbers to check for a match. All numbers must match to get a Bingo
(5) Display frequency of the game's generated numbers
    Display the ammount of times that each number was generated by the game
(6) End program
    The program terminates
Author Name: Andrea Treacy
Compiler: Borland
Date: 13/05/2020
*/

#include <stdio.h>
#include <stdlib.h>

//symbolic names
#define SIZE 6
#define CHOICESIZE 10  
#define FREQSIZE 60 //the program can store all the numbers entered for 10 rounds (this can be made bigger if it needs to be)



//function signatures
int enterNumbers(int[]);
int generateGameNumbers(int[], int[]);
void displayNumbers(int[], int[]);
void compareNumbers(int[], int[]);
void DisplayFrequencyOfNumbers(int[]);
int exit(void);


int main()
{
    int end = 0;
    int frequency_no[FREQSIZE] = {0};   //this array will store all the numbers generated over multiple rounds
    int userNumbers[SIZE];
    int gameNumbers[SIZE];
    
    //validation variables
    int numbersPicked = 0;
    int gameNumbersAssigned = 0;
    
    
    
    // The program will keep returning to menu until the user ends the program
    do
    {
        char choice[CHOICESIZE]; //made to store 10 characters in case the user enters too many. Its better to have extra space for them
        int menuChoice;
        
        printf("\n\n__________Menu__________");
        printf("\n1. Enter player's 6 numbers");
        printf("\n2. Generate game's 6 random numbers");
        printf("\n3. Display both player and game number sets");
        printf("\n4. Compare the player and game numbers");
        printf("\n5. Display frequency of the game's generated numbers");
        printf("\n6. Exit the program");
        printf("\n________________________\n\n");
        
        // user input will be taken in as a string to allow for error checking
        scanf("%s", &choice);
        
        // converting choice to an int value (if the user has entered a character its value will be 0)
        menuChoice = atoi(choice);
        
        // Checking the number the user entered 
        switch(menuChoice)
        {
            case 1:
            {
                // user gets their code
                numbersPicked = enterNumbers(userNumbers); //the value of numbersPicked will be used to check if the user can select other menu options
                break;
            }// end case 1
        
            case 2:
            {
                gameNumbersAssigned = generateGameNumbers(gameNumbers, frequency_no); //the value of gameNumbersAssigned will be used to check if the user can select other menu options
                break;
            }// end case 2
            
            case 3:
            {
                // if the user has not completed option 1 and 2 they can't access this option
                if(numbersPicked == 1 && gameNumbersAssigned == 1)
                {
                    // display users numbers and game numbers
                    displayNumbers(userNumbers, gameNumbers);
                }//end if
                
                else
                {
                    printf("\nYou must choose your numbers and generate game numbers before you can display them");
                }
                break;
            }// end case 3
            
            case 4:
            {
                // if the user has not completed option 1 and 2 they can't access this option
                if(numbersPicked == 1 && gameNumbersAssigned == 1)
                {
                    compareNumbers(userNumbers, gameNumbers);
                }
                else
                {
                    printf("\nYou must choose your numbers and generate game numbers before you can compare them");
                }
                break;
            }// end case 4
            
            case 5:
            {
                // if the user has not completed option 3 they can't access this option
                if(numbersPicked == 1 && gameNumbersAssigned == 1)
                {
                    // Display frequency of the game’s generated numbers
                    DisplayFrequencyOfNumbers(frequency_no);
                }
                else
                {
                    printf("\You must choose your numbers and generate game numbers before you can display the frequency of the game’s generated numbers");
                }
                break;
            }// end case 5
            
            case 6:
            {
                // end the program
                end = exit();   //after this function end will be equal to 1 and the do while loop will end
                break;
            }// end case 6
            
            default:
            {
                printf("\nError. Invalid number. You must choose 1 - 6");
            }
        
        }// end switch
        
    }// end do
    
    //if end == 1 the program will end
    while(end == 0);
    
    
    flushall();
    
    getchar();
    return 0;
    
} // end main





// function that allows the user to enter their own 6 numbers
int enterNumbers(int user_nos[])
{
    int nos_chosen = 0;
    int i;
    int j;
    int tmp;
    char temp[CHOICESIZE];
    int number;
    int errorCount;
    
    printf("\n1. Enter player's numbers");
    
     //this loop will run until the user correctly enters their 6 numbers
    do
    {
        errorCount = 0;
        
        //initialising all elements in the array to 0 (clearing any previously entered values)
        for(i=0; i<SIZE; i++)
        {
            *(user_nos + i) = 0;
        }
        
        printf("\nEnter your 6 numbers\n");
                
        // take in the users numbers
        for(i=0; i<SIZE; i++)
        {
            // user input will be taken in as a string to allow for error checking
            scanf("%s", &temp); 
                    
            // converting choice to an int value (if the user has entered a character its value will be 0)
            number = atoi(temp);
                    
            //check if the user's number is within the range 0-10
            if(number<0 || number>=10)
            {
                errorCount++;
            }
            else
            {
                *(user_nos + i) = number;
            }
                    
        }//end for
            
        
        //check for duplicates
        for(i=0; i<SIZE-1; i++) 
        {
            for(j=i+1; j<SIZE; j++) 
            {
                if(*(user_nos + i) == *(user_nos + j))
                {
                    errorCount++;
                }//end if
            }//end inner for
        } //end outer for 
        
        
                
        if(errorCount>0)
        {
            printf("\nError. Invalid numbers");
        }
        else
        {
            nos_chosen = 1;  //this will allow the do while loop to end
        }
                
    }//end do
            
    //when the user has entered their code correctly nos_chosen will be equal to 1
    while(nos_chosen == 0);
                
    //display the user's numbers
    printf("\nYour Numbers: ");
    for(i=0; i<SIZE; i++)
    {
        printf("%d ", *(user_nos + i));
    }
        
    
    //using bubble sort to arrange the array elements from smallest to largest
    for(i=0; i<SIZE-1; i++)
    {
        for(j=0 ; j<SIZE-i-1; j++)
        {
          if(*(user_nos + j) > *(user_nos + j + 1))
          {
              tmp = *(user_nos + j);
              *(user_nos + j) = *(user_nos + j + 1);
              *(user_nos + j + 1) = tmp;
              
          }//end if
          
        }//end inner for
        
    }//end outer for
    
    printf("\nNumbers stored successfully");
                
        
    return nos_chosen;   //this value will be needed in main for accessing other menu options
    
}//end enterNumbers()





//function that generates the game's 6 numbers
int generateGameNumbers(int game_nos[], int frequencyNums[])
{
    int perfectSet = 0;
    int i;
    int j;
    int duplicate;
    int number;
    int temp;
    
    // this variable needs to be static as it needs to retain its value every time the function is called in order to not overwrite array elements
    static int fIndex = 0;
    
    printf("\n2. Generate game's numbers\n");
    
    printf("\nGenerating a random set of numbers");
            
    do
    {
        duplicate = 0;
        
        //initialising all elements in the array to 0 (clearing any previously entered values)
        for(i=0; i<SIZE; i++)
        {
            *(game_nos + i) = 0;
        }
        
        //assign the game 6 random numbers (none can be the same)
        for(i=0; i<SIZE; i++)
        {
            // number is assigned a random number between 0 and 10
            number = rand() % 11 + 1;
            *(game_nos + i) = number;
        }
            
        //check for duplicates
        for(i=0; i<SIZE-1; i++) 
        {
            for(j=i+1; j<SIZE; j++) 
            {
                if(*(game_nos + i) == *(game_nos + j))
                {
                    duplicate++;
                }//end if
            }//end inner for
        } //end outer for 
        
        
        
        
        //if no duplicates are found its a perfect set
        if(duplicate==0)
        {
            printf("\nGame Numbers: ");
            // display the game's numbers
            for(i=0; i<SIZE; i++)
            {
                printf("%d ", *(game_nos + i));
            }
            perfectSet = 1;
        }
        else
        {
            if(duplicate>10)
            {
                perfectSet=1;
            }
        }
        
    }//end do
    while(perfectSet==0);
        
    
    //using bubble sort to arrange the array elements from smallest to largest
    for(i=0; i<SIZE-1; i++)
    {
        for(j=0 ; j<SIZE-i-1; j++)
        {
          if(*(game_nos + j) > *(game_nos + j + 1))
          {
              temp = *(game_nos + j);
              *(game_nos + j) = *(game_nos + j + 1);
              *(game_nos + j + 1) = temp;
              
          }//end if
          
        }//end inner for
        
    }//end outer for
    
    
    // adding the generated numbers to the frequencyNums array
    //  frequencyNums can only store the numbers for 10 rounds (this can be made bigger by changing FREQSIZE)
    if(fIndex>=FREQSIZE)
    {
        printf("\nNo more frequencies can be stored");
    }
    else
    {
        //  add the numbers to the frequencyNums array
        for(i=0; i<SIZE; i++)
        {
            *(frequencyNums + fIndex) = *(game_nos + i);
            fIndex++;   //this variable will retain its index position as it is static
                
        }//end for
                
    }//end else
    
        
    printf("\nNumbers stored successfully");
    
    return perfectSet;
    
}//end generateGameNumbers()






// function to display the user and game numbers
void displayNumbers(int u_nums[], int g_nums[])
{
    printf("\n3. Display numbers\n");
    
    int i;
    
    printf("\nUser Numbers: ");
    
    // display the user's numbers
    for(i=0; i<SIZE; i++)
    {
        printf("%d ", *(u_nums + i));
    }
    
    printf("\nGame Numbers: ");
    
    // display the game's numbers
    for(i=0; i<SIZE; i++)
    {
        printf("%d ", *(g_nums + i));
    }
    
}//end displayNumbers()







// function to compare the user's numbers to the game's numbers to check for a bingo
void compareNumbers(int num_user[], int num_game[])
{
    int match = 0;
    int i;
    int j;
    
    printf("\nUser numbers: ");
    
    // displaying the users numbers
    for(i=0; i<SIZE; i++)
    {
        printf("%d ", *(num_user + i));
    }
    
    printf("\nGame numbers: ");
    
    // displaying the winning numbers
    for(i=0; i<SIZE; i++)
    {
        printf("%d ", *(num_game + i));
    }
    
    
    // checking if the users numbers match the game numbers
    for(i=0; i<SIZE; i++)
        {
            for(j=0; j<SIZE; j++)
            {
                // count the number of matches
                if(*(num_user + i) == *(num_game + j))
                {
                    match++;    
                }//end if
                
            }//end inner for
            
        }//end outer for
        
    printf("\nYou have %d match(es)", match);
        
    if(match==6)
    {
        printf("\nBingo!!");
    }
    else
    {
        printf("\nYou lose!");
    }
    
}//end compareNumbers()








// function to display the frequency of the numbers generated for the game
void DisplayFrequencyOfNumbers(int frequency_array[])
{
    printf("\n5. Display frequency of the numbers generated by the game\n");
    
    int i;
    int j;
    int temp;
    int counter;
    int occurrence[FREQSIZE] = {0};     //this array will store the ammount of times each number in frequency_array occurs
    int frequency_array_copy[FREQSIZE];     //copy of frequency_array
    
    
    printf("\nNumbers generated: ");
    
    // display a list of all the numbers generated over all rounds
    for(i=0; i<FREQSIZE; i++)
    {
        //do not print anything if the number is 0 as all unused elements in the array are 0
        if(*(frequency_array + i) == 0)
        {
            printf("");
        }
        else
        {
            printf("%d ", *(frequency_array + i));
        }
    }//end for
    
    
    // making a copy of frequency_array as some elements will be overwritten while counting the number of occurrences
    for(i=0; i<FREQSIZE; i++)
    {
        *(frequency_array_copy + i) = *(frequency_array + i);
    }
    
    
    // using bubble sort so the frequencies will be displayed in ascending order
    for (i=0; i<FREQSIZE-1; i++)
    {
        for (j=0 ; j<FREQSIZE-i-1; j++)
        {
            if (*(frequency_array + j) > *(frequency_array + j + 1))
            {
              temp = *(frequency_array + j);
              *(frequency_array + j) = *(frequency_array + j + 1);
              *(frequency_array + j + 1) = temp;
              
            }//end if
          
        }//end inner for
        
    }//end outer for
    
    
    
    // fill the occurrence array with the number of occurences of each number in frequency_array
    for(i=0; i<FREQSIZE; i++)
    {
        counter = 1;    //counter starts at 1 because each number in frequency_array has been entered at least once
        
        // perform this check on all elements greater than 0
        if(*(frequency_array + i)>0)
		{
		    for(j=i+1; j<FREQSIZE; j++)
            {
                // for every occurance of the same number in frequency_array add 1 to counter
                if(*(frequency_array + i) == *(frequency_array + j))
        	    {
                    counter++;
                    
                    //this line will overwrite array elements with 0 so the same number won't be counted twice
                    *(frequency_array + j) = 0;  
                    
                }//end inner if
                
	       }//end inner for
           
           // populating the occurrence array with frequencies
	       *(occurrence + i) = counter;
           
		}//end outer if
        
    }//end outer for
    
    
    
    // displaying the numbers entered and their corresponding frequencies
    for(i=0; i<FREQSIZE; i++)
    {
        // only prints for elements greater than 0
        if(*(frequency_array + i)>0)
        {
        	printf("\nNumber %d was randomly selected %d time(s)", *(frequency_array + i), *(occurrence + i));
		}//end if
        
    }//end for
    
    
    //giving frequency_array its overwritten values back
    for(i=0; i<FREQSIZE; i++)
    {
        *(frequency_array + i) = *(frequency_array_copy + i);
    }
    
}//end DisplayFrequencyOfNumbers()








// function that will end the program by returning 1 to main
int exit()
{
    printf("\n7. Exit program\n");
    
    int shutDown = 1;
    printf("\nSystem is shutting down...");
    printf("\nPress enter to exit");
    
    // passing shutDown back to main() which wll end the program
    return shutDown;
    
}//end exit()







